### ISSUE TITLE
Firstly THANKS.... But several issues I would like to share!

### ISSUE THREAD

**Issue by exm316** [Da0ne/DZMods#30] opened 2018-11-07 19:10 UTC
Firstly thanks for updating so quickly....

Just to let you know that there are several new issues present!

1. a small 's' before every server message
2. All Admin commands show up on screen for all players to see - THIS IS A BIG ISSUE
3. /tppm does not work (says nothing in game) whereas /tpp does and so does /tpc and /tpto
4. /godmode not working again - says in game not recognised command
5. /stamina not working - says not recognised command
6. /spawncar works - but the car does not start

I have not tried some of the other commands yet, as in /kill /killall /strip /ammo etc.

Again thanks for being so active and updating so quickly, just thought I would let you know!

EXM

**Comment by exm316** [comment] 2018-11-08 09:53
The car is an easy fix.... it currently does not spawn with a Radiator, so add that in the script as an attachment and if it spawns with all required fluids/fuel it should start!

**Comment by pilonull** [comment] 2018-11-08 09:55
Funny thing is I had a pristine radiator and added it to the car and it
still didn't start

**Comment by GrosTon1** [comment] 2018-11-08 10:10
Can you please take a screenshot of the spawned car's inventory ? Is there 2 spark plugs ? The cars need 2 of them now.

**Comment by Da0ne** [comment] 2018-11-08 10:55
Thanks for the awesome feedback guys, I’m sorry I forgot to mention the knows issues in the update.

The command /tppm is now /tpm 
The vehicles need to have fuel, so I will add that so it spawns with fuel and oil
The admin messages/commands are gonna have to show up, the workaround is not useful and not 100% functional. With the implementation of client side support this issue will be squashed. 
As for the ‘s’ before every message is not a bug within the tools, but there seems to be an issue with the chat channels. I will be making a notification system fully custom for my mod,(will be included within the client side support)
Now that the workshop is up! Which great!!
The server and client files will be in the workshop (first will launch the server files) then the client t updates will be introduced as I finish on planned features. I will however keep this GITpost updated to match the workshop. Apart from that, as a server owner the installation and update is going to be still manual until there is a way to use workshop properly with server files.

**Comment by BorizzK** [comment] 2018-11-08 15:32
exm316
How to attach fluids/fuel ???
What id's of fluids/fuel?
ThanX

**Comment by S4MT3K** [comment] 2018-11-08 17:20
> 
> 
> exm316
> How to attach fluids/fuel ???
> What id's of fluids/fuel?
> ThanX

To spawn a vehicle with attachments look in the file "Spanwabletypes". look the code, try to understand how it works and add the wanted content in there.
EXAMPLE: 

In the Normal file u see that the headlights will spawn with an chance of 0.40 that means afaik 40% if you want to spawn that with an higher ratio just increase the value (BOLD):
You can also add other attachments to the spawntable: (Cursiv)
<type name="OffroadHatchback">
		<attachments chance="1.00">
			<item name="HatchbackWheel" chance="0.60" />
        </attachments>
		<attachments chance="1.00">
			<item name="HatchbackWheel" chance="0.60" />
        </attachments>
		<attachments chance="1.00">
			<item name="HatchbackWheel" chance="0.40" />
        </attachments>
		<attachments chance="1.00">
			<item name="HatchbackWheel" chance="0.40" />
        </attachments>
		<attachments chance="1.00">
			<item name="HatchbackWheel" chance="0.20" />
        </attachments>
		<attachments chance="1.00">
			<item name="CarRadiator" chance="0.20" />
        </attachments>
		<attachments chance="1.00">
			<item name="CarBattery" chance="0.30" />
        </attachments>
		<attachments chance="1.00">
			<item name="HeadlightH7" chance="0.**40**" /> 
        </attachments>
		<attachments chance="1.00">
			<item name="_CarBattery_" chance="0.**90**" /> 
        </attachments>
		<attachments chance="1.00">
			<item name="HatchbackDoors_Driver" chance="0.30" />
        </attachments>
		<attachments chance="1.00">
			<item name="HatchbackDoors_CoDriver" chance="0.30" />
        </attachments>
		<attachments chance="1.00">
			<item name="HatchbackHood" chance="0.20" />
        </attachments>
		<attachments chance="1.00">
			<item name="HatchbackTrunk" chance="0.20" />
		</attachments>
	</type>

**Comment by exm316** [comment] 2018-11-08 17:34
Forget everything - the latest update has broken everything for me!
#

**Comment by S4MT3K** [comment] 2018-11-08 17:41
> 
> 
> Forget everything - the latest update has broken everything for me!

Yes for me too. I cant spawn Zombies, building, or anything else. The tick scheduler doesnt work anymore. Aidrops (Mov3ax mod) just spawns the container on the ground instead of letting him fall... Only thing that works is playercounter ^^ ( i only use codesnippets by the way, but it worked before, so we have the same problem rn)

**Comment by robotstar78** [comment] 2018-11-08 17:47
Hmm. Mine is working fine with the latest build. Didn’t need to tweak anything either, it all just went in as built. The only thing I changed was I didn’t use custom buildings. As I’m really struggling to get it to spawn in the correct loot in the right places I’ve just turned that feature off
    	
    	

    	Get Outlook for iOS
    
  




On Thu, Nov 8, 2018 at 5:41 PM +0000, "S4MT3K" <notifications@github.com> wrote:













Forget everything - the latest update has broken everything for me!



Yes for me too. I cant spawn Zombies, building, or anything else. The tick scheduler doesnt work anymore. Aidrops (Mov3ax mod) just spawns the container on the ground instead of letting him fall... Only thing that works is playercounter ^^ ( i only use codesnippets by the way, but it worked before, so we have the same problem rn)

**Comment by exm316** [comment] 2018-11-08 19:28
My server starts fine, but once logged in as admin no admin controls work!!!!

**Comment by pilonull** [comment] 2018-11-09 00:10
yea I think the most recent dayz update broke this mod/scripts
gotta wait for dev to update them

**Comment by Da0ne** [comment] 2018-11-09 14:30
Just an FYI: if you mod this mission and add other mods from you/other modders. It is not my issue/problem if the mission breaks. its either due to the way i structure my mission OR your installation was poor/incorrect of the "foreign mod".

Atm im waiting for a more stable build within the upcoming weeks. I will be doing the release of this mission the the steam workshop, it will be on the ServerMods section, this will happened in the following few weeks. I will also drop the first client side mod that functions along side this mission. it will include many features. Such as Spawn GUI, Admin tools GUI, Notification system ( custom killfeed, login/log, custom admin global notifications ) and MORE. Stay tuna :P

**Closed** 2018-11-09 14:33 UTC

**Comment by robotstar78** [comment] 2018-11-09 14:52
Without doubt the most useful, brilliant mod that this game is ever likely to see. I can't wait to see the final release. Thanks so much for all your work on perhaps the most broken game ever developed. You're a star!

**Comment by exm316** [comment] 2018-11-09 15:14
Yep, thanks @Da0ne amazing and cant wait to try your client side mods!!!
